Get started のSetting up p5.js with an editor on your own computerを翻訳
endoh0509/p5.js-website pull request #9
Opened 2023-03-22 08:33 UTC by kikpond15

Setting up p5.js with an editor on your own computerを翻訳しました．
リンクと文章の接続が少し不安なので，確認よろしくお願いします．

2023-03-22 08:54 UTC, enkatsu commented
@kikpond15 末尾のリンクへの対応が難しいので、とりあえずは上記のコメントのみ対応でいいと思います！

2023-03-23 07:23 UTC, enkatsu requested changes
コメントの内容の修正をお願いします！

2023-03-23 07:23 UTC, enkatsu commented on src/data/en.yml
> +  environment1: '自分のコンピュータにp5.jsを実行するには、コードエディタが必要です。 あなたの好きな '
「自分のコンピュータにp5.js」は
「自分のコンピュータ上でp5.js」の方がいいかもです！

2023-03-23 07:23 UTC, enkatsu commented on src/data/en.yml
>    environment2: ' code editor '
上で「コードエディタ」と訳してるから「 code editor 」も訳しちゃっていいかもです！

2023-03-23 07:26 UTC, kikpond15 commented on src/data/en.yml
> +  environment1: '自分のコンピュータにp5.jsを実行するには、コードエディタが必要です。 あなたの好きな '
自分的に硬すぎない様な文章がいいかなと思って，「自分のコンピュータに」にしたのですが．如何でしょうか？

2023-03-23 07:27 UTC, enkatsu commented on src/data/en.yml
> +  environment1: '自分のコンピュータにp5.jsを実行するには、コードエディタが必要です。 あなたの好きな '
そしたら「自分のコンピュータでp5.jsp5.jsを実行するには、コードエディタが必要です。」でどうでしょう？

2023-03-23 07:28 UTC, kikpond15 commented on src/data/en.yml
>    environment2: ' code editor '
はい，良いと思います．それで修正いたします．

2023-03-23 07:57 UTC, enkatsu approved these changes
修正ありがとう！

2023-03-23 07:57 UTC, merged